### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by iantiktaktoe** [ecarlson94/vscode-flutter-dev-container#2]
Hi

Trying to follow the steps but it's failing on build and I'm not sure why

`[+] Building 68.4s (9/10)
 => [internal] load build definition from Dockerfile-with-features         0.0s
 => => transferring dockerfile: 4.07kB                                     0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for docker.io/library/ubuntu:latest           0.0s
 => [dev_container_auto_added_stage_label 1/7] FROM docker.io/library/ubu  0.0s
 => CACHED [dev_container_auto_added_stage_label 2/7] RUN  apt update  &&  0.0s
 => CACHED [dev_container_auto_added_stage_label 3/7] RUN APT-GET autorem  0.0s
 => CACHED [dev_container_auto_added_stage_label 4/7] RUN GROUPADD --gid   0.0s
 => CACHED [dev_container_auto_added_stage_label 5/7] RUN curl -C - --out  0.0s
 => ERROR [dev_container_auto_added_stage_label 6/7] RUN  sdkmanager "sy  68.3s
------
 > [dev_container_auto_added_stage_label 6/7] RUN  sdkmanager "system-images;and
roid-33;google_apis;x86_64"      && avdmanager create avd -n Android33 -k "syste
m-images;android-33;google_apis;x86_64":
#9 1.994 Loading package information...
[=======================================] 100% Unzipping... x86_64/data/misc/mod
#9 67.90 Loading local repository...
Auto-selecting single ABI x86_64========] 100% Fetch remote repository...
#9 68.21 Do you wish to create a custom hardware profile? [no] offset 0, count -
1, length 256
------
error: failed to solve: executor failed running [/bin/sh -c sdkmanager "system-i
mages;android-${ANDROID_PLATFORM_VERSION};google_apis;x86_64"    && avdmanager c
reate avd -n Android${ANDROID_PLATFORM_VERSION} -k "system-images;android-${ANDR
OID_PLATFORM_VERSION};google_apis;x86_64"]: exit code: 1
[74609 ms] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f C:\Users\Ian\AppData\Local\Temp\devcontainercli\container-features\0.29.0-1675605529067\Dockerfile-with-features -t vsc-flutter-dev-container-421d5355087fab30e642f834c99e5e5b --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label d:\Work\FlutterDev\projects\flutter-dev-container\.devcontainer
[74609 ms]     at pie (c:\Users\Ian\.vscode\extensions\ms-vscode-remote.remote-containers-0.275.0\dist\spec-node\devContainersSpecCLI.js:1916:1698)
[74610 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[74610 ms]     at async vF (c:\Users\Ian\.vscode\extensions\ms-vscode-remote.remote-containers-0.275.0\dist\spec-node\devContainersSpecCLI.js:1915:1972)
[74610 ms]     at async P7 (c:\Users\Ian\.vscode\extensions\ms-vscode-remote.remote-containers-0.275.0\dist\spec-node\devContainersSpecCLI.js:1915:901)
[74610 ms]     at async Fie (c:\Users\Ian\.vscode\extensions\ms-vscode-remote.remote-containers-0.275.0\dist\spec-node\devContainersSpecCLI.js:1921:2093)
[74610 ms]     at async Vf (c:\Users\Ian\.vscode\extensions\ms-vscode-remote.remote-containers-0.275.0\dist\spec-node\devContainersSpecCLI.js:1921:3241)
[74610 ms]     at async eoe (c:\Users\Ian\.vscode\extensions\ms-vscode-remote.remote-containers-0.275.0\dist\spec-node\devContainersSpecCLI.js:2045:17324)
[74610 ms]     at async Qse (c:\Users\Ian\.vscode\extensions\ms-vscode-remote.remote-containers-0.275.0\dist\spec-node\devContainersSpecCLI.js:2045:17065)
[74620 ms] Exit code 1
[74624 ms] Command failed: C:\Users\Ian\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\Ian\.vscode\extensions\ms-vscode-remote.remote-containers-0.275.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\Ian\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --container-session-data-folder tmp/devcontainers-db9859e4-fbb5-4b56-a2af-cc2ff00bf4911675605524034 --workspace-folder d:\Work\FlutterDev\projects\flutter-dev-container --workspace-mount-consistency cached --id-label devcontainer.local_folder=d:\Work\FlutterDev\projects\flutter-dev-container --id-label devcontainer.config_file=d:\Work\FlutterDev\projects\flutter-dev-container\.devcontainer\devcontainer.json --log-level debug --log-format json --config d:\Work\FlutterDev\projects\flutter-dev-container\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[74624 ms] Exit code 1`

Any advice?

thanks

**Comment by ecarlson94** [comment]
Awe man. I'm sorry that I did not see this sooner. I don't even use this anymore. I just use `cirrusci/flutter` as a base now. Here is what my most recent [devcontainer Dockerfile](https://github.com/ecarlson94/mascot/blob/main/.devcontainer/Dockerfile) looks like. It is much simpler than this nonsense.

Once again, I am so sorry for not seeing this sooner. I will archive this repo with a readme in the update so that nobody else follows your footsteps.

**Comment by ecarlson94** [comment]
I should also mention that I only use Flutter dev containers for web development. While the whole adb bridge thing can be done with Docker, it is often more of a hassle than it is worth. I use my browsers DevTools to force mobile viewports for development.
